


CREATE DATABASE UNIVERSITY
GO




USE UNIVERSITY
GO


DROP TABLE STUDENTS


--CONSTRAINTS - შეზღუდვები

CREATE TABLE STUDENTS
(
ID INT PRIMARY KEY IDENTITY(1,1),
FirstName NVARCHAR(50)  NOT NULL, 
Eamil VARCHAR(255) NOT NULL UNIQUE,
Age INT NOT NULL CHECK(AGE BETWEEN 18 AND 100), 
GPA DECIMAL(3,2) CHECK(GPA BETWEEN 0.00 AND 4.00),   -- 3.25 
IsActive BIT DEFAULT(1),
RegisteredAt DATETIME2 DEFAULT(SYSDATETIME())
 
)






INSERT INTO STUDENTS
(  
FirstName,  Eamil,  Age,  GPA, PhoneNumber
)
VALUES
(N'ლანა3','DFDFDF@GMAIL7857', 36, 0.02,'+995585858'),
(N'ლანა12','DFDFDF@GMAIL5667', 36, 0.02,'+995585858'),
(N'ლანა1','DFDFDF@GMAIL6667', 36, 0.02,'+995585858')


ALTER TABLE STUDENTS
ADD PhoneNumber VARCHAR(20) NULL 



DELETE FROM STUDENTS 
 where FirstName = N'ლანა12'


 UPDATE STUDENTS 
 SET GPA = 3.25
 WHERE ID=3


 /*
SELECT S.* ,
       F.DepartmentName
FROM STUDENTS S
LEFT JOIN FACULTY F ON S.DepartmentID = F.DepartmentID
*/

SELECT S.FirstName ,
       F.DepartmentName
FROM STUDENTS S
JOIN FACULTY F ON S.DepartmentID = F.DepartmentID


ALTER TABLE STUDENTS
--ADD DepartmentID INT NULL
ADD CONSTRAINT FK_STUDENTS_FACULTY FOREIGN KEY (DepartmentID) REFERENCES FACULTY(DepartmentID)


CREATE TABLE FACULTY
(
  DepartmentID INT PRIMARY KEY IDENTITY(1,1),
  DepartmentName NVARCHAR(100) NOT NULL
)


SELECT * FROM FACULTY

INSERT INTO FACULTY
(DepartmentName)
VALUES
('Medical Science')




INSERT INTO STUDENTS
(  
FirstName,  Eamil,  Age,  GPA, PhoneNumber, DepartmentID
)
VALUES
(N'ლანა3','DFDFDF@GMAIL785789', 36, 0.02,'+995585858', 1),
(N'ლანა12','DFDFDF@GMAIL5667899', 36, 0.02,'+995585858', 2),
(N'ლანა1','DFDFDF@GMAIL666789', 36, 0.02,'+995585858', 6)



--TEST
--RELATIONSHIPS
-- ONE TO MANY 
-- ONE TO ONE
-- MANY TO MANY


SELECT *
FROM STUDENTS


SELECT COUNT(*)
FROM STUDENTS


SELECT COUNT(DISTINCT FirstName)
FROM STUDENTS


SELECT SUM(AGE)
FROM STUDENTS

SELECT AVG(AGE)
FROM STUDENTS


SELECT MIN(GPA)
FROM STUDENTS

SELECT MAX(GPA)
FROM STUDENTS


SELECT FirstName + ' - ' + Eamil as FullInfo from STUDENTS


SELECT * FROM STUDENTS
WHERE GPA > 0.01
ORDER BY GPA DESC

SELECT * FROM STUDENTS
WHERE GPA > 0.01
ORDER BY GPA ASC


SELECT COUNT(FirstName), FirstName
FROM STUDENTS
GROUP BY FirstName


SELECT FirstName, LEN(FirstName)
FROM STUDENTS

-- სტრინგის ფუნქციები
SELECT LEN('AAA')
SELECT TRIM(' AAA ')
SELECT LTRIM(' AAA ')
SELECT RTRIM(' AAA ')


SELECT REPLACE(N'გიორგი', N'გ', N'G')
SELECT SUBSTRING('HELLO', 2, 3)

SELECT LEFT('HELLO', 2)
SELECT RIGHT('HELLO', 2)


SELECT UPPER('george')


SELECT LOWER('georgE')



--დაასელექტეთ ისეთი სტუდენტების სია რომელსაც ფაკულტეტის სახელი აქვს 5 სიმბოლოზე მეტი


--like '%Science%'


SELECT s.FirstName , f.DepartmentName
from STUDENTS s
join FACULTY f on s.DepartmentID = f.DepartmentID
where f.DepartmentName like '%Science%'





SELECT SYSDATETIME()
SELECT GETDATE()

SELECT DATEPART(YEAR, '2025-04-01')
SELECT DATEPART(MONTH, '2025-04-01')
SELECT DATEPART(DAY, '2025-04-01')
SELECT DATEPART(WEEK, '2025-04-01')


SELECT YEAR('2025-01-20')

SELECT DATEDIFF(MONTH, '2020-04-01', '2026-04-01')
SELECT DATEDIFF(YEAR, '2020-04-01', '2026-04-01')
SELECT DATEDIFF(WEEK, '2020-04-01', '2026-04-01')
SELECT DATEDIFF(DAY, '2020-04-01', '2026-04-01')


SELECT DATEADD(YEAR, 5, '2020-04-01')
SELECT DATEADD(MONTH, 5, '2020-04-01')